In [102]:
import pandas as pd
features = pd.read_csv('./data/breast-cancer-wisconsin.data.txt',names = ["Sample Code number", "Clump Thickness", "Uniformity of Cell Size", "Unfiformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size", "Bare Nuclei", "Bland Chromatin", "Normal Nucleol", "Mitoses", "Class"])
features.head()

,Sample Code number,Clump Thickness,Uniformity of Cell Size,Unfiformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bare Nuclei,Bland Chromatin,Normal Nucleol,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2

In [103]:
features = pd.get_dummies(features)
features.head()

,Sample Code number,Clump Thickness,Uniformity of Cell Size,Unfiformity of Cell Shape,Marginal Adhesion,Single Epithelial Cell Size,Bland Chromatin,Normal Nucleol,Mitoses,Class,...,Bare Nuclei_10,Bare Nuclei_2,Bare Nuclei_3,Bare Nuclei_4,Bare Nuclei_5,Bare Nuclei_6,Bare Nuclei_7,Bare Nuclei_8,Bare Nuclei_9,Bare Nuclei_?
0,1000025,5,1,1,1,2,3,1,1,2,...,0,0,0,0,0,0,0,0,0,0
1,1002945,5,4,4,5,7,3,2,1,2,...,1,0,0,0,0,0,0,0,0,0
2,1015425,3,1,1,1,2,3,1,1,2,...,0,1,0,0,0,0,0,0,0,0
3,1016277,6,8,8,1,3,3,7,1,2,...,0,0,0,1,0,0,0,0,0,0
4,1017023,4,1,1,3,2,3,1,1,2,...,0,0,0,0,0,0,0,0,0,0

In [104]:
import numpy as np
labels = np.array(features['Class'])
features = features.drop('Class',axis=1)

In [105]:
from sklearn.model_selection import train_test_split
Xtrain, Xtest, ytrain, ytest = train_test_split(features, labels, test_size = 0.25, random_state = 42)

print('Training Features Shape:', Xtrain.shape)
print('Training Labels Shape:', ytrain.shape)
print('Testing Features Shape:', Xtest.shape)
print('Testing Labels Shape:', ytest.shape)

Training Features Shape: (524, 20)
Training Labels Shape: (524,)
Testing Features Shape: (175, 20)
Testing Labels Shape: (175,)

In [106]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100)
model.fit(Xtrain, ytrain)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [108]:
names = features
print("Features sorted by their score:")
print(sorted(zip(map(lambda x: round(x, 4), model.feature_importances_), names), 
reverse=True))

Features sorted by their score:
[(0.2094, 'Uniformity of Cell Size'), (0.2041, 'Unfiformity of Cell Shape'), (0.1301, 'Bland Chromatin'), (0.121, 'Single Epithelial Cell Size'), (0.0864, 'Normal Nucleol'), (0.0532, 'Clump Thickness'), (0.052, 'Marginal Adhesion'), (0.0421, 'Bare Nuclei_1'), (0.0392, 'Bare Nuclei_10'), (0.0179, 'Sample Code number'), (0.016, 'Mitoses'), (0.0079, 'Bare Nuclei_?'), (0.0037, 'Bare Nuclei_5'), (0.0035, 'Bare Nuclei_8'), (0.0031, 'Bare Nuclei_7'), (0.003, 'Bare Nuclei_2'), (0.0023, 'Bare Nuclei_3'), (0.0022, 'Bare Nuclei_4'), (0.0021, 'Bare Nuclei_6'), (0.0007, 'Bare Nuclei_9')]

In [ ]:
ypred = model.predict(Xtest)

from sklearn import metrics
print(metrics.classification_report(ypred, ytest))

In [ ]:
from sklearn.metrics import confusion_matrix
import seaborn as sns; sns.set()
%matplotlib inline 
import matplotlib.pyplot as plt

mat = confusion_matrix(ytest, ypred)
sns.heatmap(mat.T, square=True, annot=True, fmt='d', cbar=False)
plt.xlabel('true label')
plt.ylabel('predicted label');